### ISSUE TITLE
INVALID_ACCESS_TOKEN error_code 从42001变成了40014

### ISSUE THREAD

**Issue by zesen-lee** [NotFound403/wecom-sdk#22]
### INVALID_ACCESS_TOKEN 最新 error_code 为 40014
![image](https://github.com/user-attachments/assets/210e85c5-bdb4-4ce3-9d3c-75a638841194)

### 代码是 42001，已过时
![image](https://github.com/user-attachments/assets/ea603614-20a2-42e6-b203-5763c7ef826d)

**Comment by NotFound403** [comment]
@blankbro   排查你是否使用了错误的应用的问题，应该是你自己的问题，并不是企微的问题   

```
API错误码
40014
错误说明:
不合法的access_token
排查方法:
access_token参数错误。确认：
1) access_token需要在有效期内调用，失效了就是会提示token非法。可以重新获取一次access_token解决
2) openapi解析不到传入的access_token，可以先检查入参是否存在非法字符，导致无法解析access_token。
3) access_token对应的应用类型不匹配，比如小程序登入流程，使用了是非小程序应用的access_token。
4) token类型用错，token分为access_token suite_access_token 和provider_access_token三种，接口对应的access_token取值是不一致的，参数名也不一样。需要确认token类型。
```

```
API错误码
42001
错误说明:
access_token已过期
排查方法:
access_token有时效性，需要重新获取一次
```

**Comment by zesen-lee** [comment]
我看到咱们sdk内部会自动判断返回的错误码是不是 invalid_access_token（42001），然后决定是否重新获取access token。
我这边确实是 access token 过期了，但返回错误码是 40014 而不是 42001。

后来我修改了你 TokenInterceptor.java 83 行的逻辑，新增了 40014 错误码的判断，最后程序正常运行了。

**Comment by zesen-lee** [comment]
![image](https://github.com/user-attachments/assets/9c70169a-d3a9-4395-aaea-0e905153f425)

这不正说明 access token 过期，是有两个错误码吗！

**Comment by NotFound403** [comment]
> 我看到咱们sdk内部会自动判断返回的错误码是不是 invalid_access_token（42001），然后决定是否重新获取access token。 我这边确实是 access token 过期了，但返回错误码是 40014 而不是 42001。
> 
> 后来我修改了你 TokenInterceptor.java 83 行的逻辑，新增了 40014 错误码的判断，最后程序正常运行了。

这个等跟企微沟通吧，他们的逻辑有问题

**Comment by zesen-lee** [comment]
我看到了最新的代码，但这么处理似乎会有问题。

https://github.com/NotFound403/wecom-sdk/blob/9a447a4b0bf88c8c310814451c62e81c56b1cdb6/wecom-objects/src/main/java/cn/felord/retrofit/TokenInterceptor.java#L91

![image](https://github.com/user-attachments/assets/00a8a643-c897-4174-9e5f-760aefa95909)

因为 40014 也是 token 过期的一种，而且上面您也提到了官方给出的解决方法之一是重新获取一下 token。

直接抛出异常，会导致过期的 token 无法刷新吧？

**Comment by NotFound403** [comment]
> 我看到了最新的代码，但这么处理似乎会有问题。
> 
> https://github.com/NotFound403/wecom-sdk/blob/9a447a4b0bf88c8c310814451c62e81c56b1cdb6/wecom-objects/src/main/java/cn/felord/retrofit/TokenInterceptor.java#L91
> 
> ![image](https://private-user-images.githubusercontent.com/31715758/398827040-00a8a643-c897-4174-9e5f-760aefa95909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjU3MzEsIm5iZiI6MTczNTI2NTQzMSwicGF0aCI6Ii8zMTcxNTc1OC8zOTg4MjcwNDAtMDBhOGE2NDMtYzg5Ny00MTc0LTllNWYtNzYwYWVmYTk1OTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAyMTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYjBjZWY0YmFjNzcwOGFlMTk1MGViYTU0YzkyZDQ0NmJiZjdmNGU0NWQ1NzNjODkzZmJjZWUzMTk5YWM2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._7ySPPAaXOf8qjEJo6FxwKJNbK2_KI9P_moRSkxMtsk)
> 
> 因为 40014 也是 token 过期的一种，而且上面您也提到了官方给出的解决方法之一是重新获取一下 token。
> 
> 直接抛出异常，会导致过期的 token 无法刷新吧？

目前它这个代码不纯粹是过期，如果是其它原因会引发死循环导致OOM，这是企微的问题，在企微解决这个问题之前，中断手动重试最合理

**Comment by zesen-lee** [comment]
企微问题大大滴，一个错误码搞出这么多错误类型，烦死啦😫
